### ISSUE TITLE
Thank you for that Brozorb, i am aware and the issue has been fixed.

### ISSUE THREAD

**Issue by brozorb** [Sulaiman-Gaskell/CalcGame#10]
Thank you for that Brozorb, i am aware and the issue has been fixed.

_Originally posted by @Sulaiman-Gaskell in https://github.com/Sulaiman-Gaskell/CalcGame/issues/8#issuecomment-1126157618_

has it really tho

**Comment by Sulaiman-Gaskell** [comment]
Yep, the branch is gone
