### ISSUE TITLE
Device support 

### ISSUE THREAD

**Issue by Sulaiman-Gaskell** [Sulaiman-Gaskell/CalcGame#12]
This game will soon be able to be played on non Windows machines, as long as it meets the other requirements.

Sounds will not be implemented on these devices due to sounds being used as win-sound.

**Comment by brozorb** [comment]
Other things that currently don't work on non Windows machines: 
- Clear currently doesn't check for platform, so errors if clr doesn't work 
- waiting for merge - file name inconsistencies fixed

**Comment by Sulaiman-Gaskell** [comment]
Merged the above and fixed clr issue
