### ISSUE TITLE
.vs directory keeps uploading

### ISSUE THREAD

**Issue by brozorb** [Sulaiman-Gaskell/CalcGame#19]
@Sulaiman-Gaskell is the .gitignore file in ur visual studio project structure. if not please add it

**Comment by Sulaiman-Gaskell** [comment]
@brozorb I will add it later if not there already. I cannot check right now.

**Comment by brozorb** [comment]
K

**Comment by Sulaiman-Gaskell** [comment]
@brozorb the .gitignore file is in my visual studio project structure.

**Comment by brozorb** [comment]
What's in it

**Comment by Sulaiman-Gaskell** [comment]
contains the following:
.vs/
.vscode/

**Comment by brozorb** [comment]
k

**Comment by brozorb** [comment]
when u next commit using vs we'll see if .vs/ comes back

**Comment by Sulaiman-Gaskell** [comment]
ok
