### ISSUE TITLE
Non-Windows.py not working on windows devices.

### ISSUE THREAD

**Issue by Sulaiman-Gaskell** [Sulaiman-Gaskell/CalcGame#20]
@brozorb  Is this a bug or should I fix it?

**Comment by brozorb** [comment]
idk why that indented but it's fixed now

**Comment by Sulaiman-Gaskell** [comment]
I also fixed it

**Comment by Sulaiman-Gaskell** [comment]
Shoudl i commit

**Comment by Sulaiman-Gaskell** [comment]
I have found some other bugs aswell

**Comment by brozorb** [comment]
what other bugs?

**Comment by Sulaiman-Gaskell** [comment]
Issue with clearing the console

**Comment by Sulaiman-Gaskell** [comment]
Message='str' object has no attribute 'system'
  Source=C:\Users\sulai\OneDrive\Documents\GitHub\CalcGame\CalculatorGame (Non-Windows).py
  StackTrace:
  File "C:\Users\sulai\OneDrive\Documents\GitHub\CalcGame\CalculatorGame (Non-Windows).py", line 24, in <lambda>
    clearConsole = lambda: os.system('cls')
  File "C:\Users\sulai\OneDrive\Documents\GitHub\CalcGame\CalculatorGame (Non-Windows).py", line 28, in <module>
    clearConsole()

**Comment by Sulaiman-Gaskell** [comment]
Dont worry i fixed it

**Comment by brozorb** [comment]
Oh yea forgot about that

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brozorb** [comment]
why did get outlook for android appear
breh

**Comment by Sulaiman-Gaskell** [comment]
lol

**Comment by brozorb** [comment]
Does this work now?
________________________________

**Comment by Sulaiman-Gaskell** [comment]
To fix it i just changed your variable os to oS due to conflict with os.system

**Comment by Sulaiman-Gaskell** [comment]
yh

**Comment by brozorb** [comment]
clicking on 3 dots is funny

**Comment by Sulaiman-Gaskell** [comment]
Y u replying in email lol

**Comment by brozorb** [comment]
easier than opening github

**Comment by Sulaiman-Gaskell** [comment]
Na

**Comment by Sulaiman-Gaskell** [comment]
Should we make the non-windows vers the main one

**Comment by brozorb** [comment]
It is tho
________________________________

**Comment by Sulaiman-Gaskell** [comment]
Its not

**Comment by brozorb** [comment]
prob

**Comment by Sulaiman-Gaskell** [comment]
K, ill get rid of the other ones, we will lose sound tho

**Comment by brozorb** [comment]
Yep
________________________________

**Comment by Sulaiman-Gaskell** [comment]
done

**Comment by brozorb** [comment]
k

**Comment by Sulaiman-Gaskell** [comment]
Do the other files, practice.py and challeader.py work aswell

**Comment by brozorb** [comment]
https://user-images.githubusercontent.com/84518177/168473233-1c75b6cb-c49b-49e2-ac4b-27964badae9b.mp4

**Comment by Sulaiman-Gaskell** [comment]
y tho

**Comment by Sulaiman-Gaskell** [comment]
Should i also rename them now

**Comment by brozorb** [comment]
even tho there was practice (non-windows) and challeader (non-windows) it was still using practice.py and challeader.py

**Comment by Sulaiman-Gaskell** [comment]
ah ok

**Comment by brozorb** [comment]
K

**Comment by Sulaiman-Gaskell** [comment]
Nice, i might start working on a new update soon so

**Comment by brozorb** [comment]
@Sulaiman-Gaskell 
when you have finished the update merge it into the releases branch. this means the install script won't install anything that's not finished

**Comment by Sulaiman-Gaskell** [comment]
@brozorb ok
