### ISSUE TITLE
practice.py still imports msvcrt

### ISSUE THREAD

**Issue by brozorb** [Sulaiman-Gaskell/CalcGame#22]
so doesn't work on linux/ android as msvcrt doesn't exist for them
![Screenshot_20220515-161217_Gallery](https://user-images.githubusercontent.com/84518177/168480048-1a4004e6-8a54-4b3f-be36-1d4769fdd7a0.jpg)
sorry for the bad quality but it only appears for about half a second

**Comment by brozorb** [comment]
@Sulaiman-Gaskell can u fix this the way you did CalculatorGame.py

**Comment by Sulaiman-Gaskell** [comment]
@brozorb sure

**Comment by Sulaiman-Gaskell** [comment]
Should work now.

**Comment by Sulaiman-Gaskell** [comment]
@brozorb pls update requirments.txt for the following:
        import sys, termios    #for linux/unix
        termios.tcflush(sys.stdin, termios.TCIOFLUSH)

**Comment by brozorb** [comment]
https://pip.pypa.io/en/latest/reference/requirements-file-format/

**Comment by brozorb** [comment]
Sys and termios are inbuilt into python

**Comment by Sulaiman-Gaskell** [comment]
ok
